# Generated by Django 3.2.8 on 2022-01-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='web',
            field=models.URLField(max_length=100),
        ),
    ]
