# Generated by Django 3.2.8 on 2022-01-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220109_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='web',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='zip',
            field=models.IntegerField(max_length=10),
        ),
    ]
